<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    
    <title>South Africa Business Advertising Map</title>
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/leaflet@1.7.1/dist/leaflet.css" />
    <script src="https://cdn.jsdelivr.net/npm/leaflet@1.7.1/dist/leaflet.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Leaflet.awesome-markers/2.0.4/leaflet.awesome-markers.min.js"></script>
    
    <style>
        html, body { width: 100%; height: 100%; margin: 0; padding: 0; }
        #map { width: 100%; height: 100vh; }
    </style>
</head>
<body>
    <div id="map"></div>

    <script>
        // Initialize the map
        var map = L.map('map').setView([-30.5595, 22.9375], 6);

        // Load tile layer
        L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            attribution: '&copy; OpenStreetMap contributors'
        }).addTo(map);

        // Business locations
        var locations = [
            { name: "Empangeni", coords: [-28.7483, 31.8931] },
            { name: "Richards Bay", coords: [-28.7748, 32.0554] },
            { name: "Port Elizabeth", coords: [-33.9608, 25.6022] },
            { name: "Pretoria Noord", coords: [-25.7313, 28.2184] },
            { name: "Cape Town", coords: [-33.9249, 18.4241] },
            { name: "Durban", coords: [-29.8587, 31.0218] },
            { name: "Johannesburg", coords: [-26.2041, 28.0473] },
            { name: "Nelspruit", coords: [-25.4793, 30.9842] },
            { name: "Sandton", coords: [-26.1076, 28.0567] },
        ];

        // Add markers
        locations.forEach(function(location) {
            L.marker(location.coords).addTo(map)
                .bindPopup(`<b>${location.name}</b>`);
        });
    </script>
</body>
</html>
